FROM ros:noetic-ros-core

LABEL maintainer="Christian Brommer <christian.brommer@aau.at>"
LABEL description="Mars Ros Wrapper Test Environment"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y \
    vim \
    wget \
    doxygen \
    graphviz \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install --no-install-recommends -y \
    libeigen3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install --no-install-recommends -y \
    python3-catkin-tools \
    ros-noetic-dynamic-reconfigure \
    ros-noetic-tf2-ros \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /catkin_ws/src
WORKDIR /catkin_ws
RUN /bin/bash -c '. /opt/ros/noetic/setup.bash; catkin build'

COPY ./docker_application_test.sh /
CMD /docker_application_test.sh
