# Copyright (C) 2022 Christian Brommer and Martin Scheiber,
# Control of Networked Systems, University of Klagenfurt, Austria.
#
# All rights reserved.
#
# This software is licensed under the terms of the BSD-2-Clause-License with
# no commercial use allowed, the full terms of which are made available
# in the LICENSE file. No license in patents is granted.
#
# You can contact the author at <christian.brommer@ieee.org>
# and <martin.scheiber@ieee.org>.

FROM ros:noetic-ros-core as stage1
LABEL author="Christian Brommer <christian.brommer@aau.at>"
LABEL author="Martin Scheiber <martin.scheiber@aau.at>"
LABEL maintainer="Christian Brommer <christian.brommer@aau.at>"
LABEL description="Mars Ros Wrapper Test Environment"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y \
    vim \
    wget \
    doxygen \
    graphviz \
    build-essential \
    libeigen3-dev \
    python3-catkin-tools \
    ros-noetic-dynamic-reconfigure \
    ros-noetic-tf2-ros \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /catkin_build_ws/src \
    && mkdir -p /catkin_make_ws/src

WORKDIR /catkin_build_ws
RUN /bin/bash -c "source /opt/ros/noetic/setup.sh; rosdep init && rosdep update; \
                  source /opt/ros/noetic/setup.sh; catkin init; catkin config --extend /opt/ros/noetic; \
                  source /opt/ros/noetic/setup.sh; catkin build;"

WORKDIR /catkin_make_ws
RUN /bin/bash -c "source /opt/ros/noetic/setup.sh; catkin_make;"

COPY ./docker_application_test.sh /

# flatten image
FROM scratch as final
COPY --from=stage1 / /

ENTRYPOINT ["/bin/bash"]
CMD /docker_application_test.sh
