name: Docker Container Build (main)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker/**'

jobs:
  build_env_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        env:
          DOCKER_USER: ${{secrets.GITLAB_REGISTRY_USER}}
          DOCKER_PASSWORD: ${{secrets.GITLAB_REGISTRY_PASSWORD}}
          DOCKER_URL: ${{secrets.GITLAB_REGISTRY_URL}}
        run: |
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} ${DOCKER_URL}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build Docker Image
        env:
          IMAGE_URL: ${{secrets.GITLAB_REGISTRY_IMAGE_URL}}
        run: >
             docker buildx build --platform=linux/amd64,linux/arm64 --tag ${IMAGE_URL}/mars_ros_test_env:latest --compress --squash --force-rm --push ./docker/
