name: ROS Builds

on:
  push:
    branches: [ "main", "development"]
  pull_request:
    branches: [ "main", "development"]

env:
  BUILD_TYPE: Release

jobs:
  noetic:
    runs-on: ubuntu-latest
    container: ros:noetic-ros-core
    steps:
    - name: Install Dependencies
      run: >
           apt-get update && apt-get install --no-install-recommends -y
           git
           doxygen
           graphviz
           build-essential
           libeigen3-dev
           python3-catkin-tools
           ros-noetic-dynamic-reconfigure
           ros-noetic-tf2-ros

    - name: Create Catkin Workspace
      run: mkdir -p ${{github.workspace}}/catkin_ws/src

    - uses: actions/checkout@v3
      with:
        path: ${{github.workspace}}/catkin_ws/src
        submodules: recursive

    - name: Build
      working-directory: ${{github.workspace}}/catkin_ws
      run: /bin/bash -c '. /opt/ros/noetic/setup.bash; catkin build -DCMAKE_BUILD_TYPE=Release;'

  melodic:
    runs-on: ubuntu-latest
    container: ros:melodic-ros-core
    steps:
    - name: Get newer Git version
      run: >
           apt-get update && apt-get install --no-install-recommends -y
           software-properties-common
           && add-apt-repository ppa:git-core/ppa

    - name: Install Dependencies
      run: >
           apt-get update && apt-get install --no-install-recommends -y
           git
           doxygen
           graphviz
           build-essential
           libeigen3-dev
           python-catkin-tools
           ros-melodic-dynamic-reconfigure
           ros-melodic-tf2-ros

    - name: Create Catkin Workspace
      run: mkdir -p ${{github.workspace}}/catkin_ws/src

    - uses: actions/checkout@v3
      with:
        path: ${{github.workspace}}/catkin_ws/src
        submodules: recursive

    - name: Build
      working-directory: ${{github.workspace}}/catkin_ws
      run: /bin/bash -c '. /opt/ros/melodic/setup.bash; catkin build -DCMAKE_BUILD_TYPE=Release;'

  kinetic:
    runs-on: ubuntu-latest
    container: ros:kinetic-ros-core
    steps:
    - name: Get newer Git version
      run: >
           apt-get update && apt-get install --no-install-recommends -y
           software-properties-common
           && add-apt-repository ppa:git-core/ppa

    - name: Install Dependencies
      run: >
           apt-get update && apt-get install --no-install-recommends -y
           git
           doxygen
           graphviz
           build-essential
           libeigen3-dev
           python-catkin-tools
           ros-kinetic-dynamic-reconfigure
           ros-kinetic-tf2-ros

    - name: Create Catkin Workspace
      run: mkdir -p ${{github.workspace}}/catkin_ws/src

    - uses: actions/checkout@v3
      with:
        path: ${{github.workspace}}/catkin_ws/src
        submodules: recursive

    - name: Build
      working-directory: ${{github.workspace}}/catkin_ws
      run: /bin/bash -c '. /opt/ros/kinetic/setup.bash; catkin build -DCMAKE_BUILD_TYPE=Release;'
